[project]
name = "mcp-browser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "browser-use>=0.11.5",
    "mcp>=1.26.0",
    "playwright>=1.57.0",
]
